# Disable sudo to speed up the build
sudo: false

dist: trusty

language: python

python:
  - "3.6"

install:
  - poetry install
  - poetry run pip install \
      codecov==2.0.15 \
      pytest==4.6.5

script:
  - poetry run coverage run --include "devops/*" -m pytest
  - poetry run coverage xml -i
  - mkdir coverage-reports
  - mv coverage.xml coverage-reports/coverage-python.xml
  - sonar-scanner

addons:
  sonarcloud:
    organization: "lieturd"
    token: $SONAR_TOKEN
